"use client";

// import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/commons/Navbar/Navbar";
// import { Provider } from "react-redux";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

//No está permitido usar Metadata con useClient
// export const metadata: Metadata = {
//   title: "House of Dev",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Provider store={store()}> */}
      <body className={montserrat.className}>
        <Navbar />
        {children}
      </body>
      {/* </Provider> */}
    </html>
  );
}
